version: '3.7'

services: 
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8-community
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
      restart_policy:
        condition: on-failure  
      ports: 
      - 9001:9000
      - 9092:9092
      networks:
        proxy:
          ipv4_address: 172.16.238.2

  nginx:
    container_name: nginx
    image: nginx
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
    depends_on:
      - vex_account
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
    networks:
      proxy:
        ipv4_address: 172.16.238.3

  postgres:
    container_name: postgres
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
      restart_policy:
        condition: on-failure
    volumes: 
      - db_data:/data/postgres
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    env_file:
      - ./db/.env.postgres
    ports: 
      - 5432:5432
    networks:
      proxy:
        ipv4_address: 172.16.238.4

  redis:
    container_name: redis
    image: redis
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
      restart_policy:
        condition: on-failure  
    restart: always
    ports: 
      - 6379:6379
    networks:
      proxy:
        ipv4_address: 172.16.238.5

  vex:
    container_name: vex
    image: leozin89/vex
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
      - redis
    restart: always
    env_file:
      - ./app/.env
    networks:
      proxy:
        ipv4_address: 172.16.238.6

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
      restart_policy:
        condition: on-failure
    volumes:
      - rabbit_mq_data/:/var/lib/rabbitmq/
    env_file:
      - ./mq/.env.rabbit.mq
    restart: always
    ports: 
      - 25672:25672 
      - 15672:15672
    networks:
      proxy:
        ipv4_address: 172.16.238.8

networks:
  proxy:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/16

volumes:
  db_data: {}
  rabbit_mq_data: {}
