version: '3'

networks:
  proxy:
    driver: bridge

volumes:
  db_data: {}

services: 
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:etc/nginx/nginx.conf
    ports: 
      - 80:80
    networks:
      - proxy

  postgres:
    image: postgres
    volumes: 
	    - db_data:/data/postgres
    restart: always
    env_file:
	    - ./.env.postgres
      - ./db/Vex_schema.sql:/docker-entrypoint-initdb.d/Vex_schema.sql
    ports: 
      - 5432:5432
    networks:
      - proxy

  redis:
    image: redis
    ports: 
      - 6379:6379
    networks:
      - proxy

  vex_account:
    depends_on:
	    - postgres
      - redis
    image: leozin89/vex_account
    networks:
      - proxy
    env_file:
	    - ./.env

